### ISSUE TITLE
Multiline

### ISSUE THREAD

**Issue by jclusso** [ezekg/language-haml#20]
multiline code highlighting doesn't work in ruby haml.

```ruby
=link_to settings_campaign_url(@campaign),
            class: active_page == "settings" ? "active" : "" do

**Comment by iRet** [comment]
I found a problem with end of attributes '}' regex it works wrong when I'm using hashes inside attributes
![image](https://cloud.githubusercontent.com/assets/46217/6481429/8e4fd38c-c287-11e4-92c5-ab365b239eaf.png)

Just created PR to fix it
![image](https://cloud.githubusercontent.com/assets/46217/6481450/cd4fc4ac-c287-11e4-8598-0afab49c9b7e.png)

**Comment by jclusso** [comment]
@iRet do you have any idea how to fix the ruby syntax?

**Comment by iRet** [comment]
@jclusso oh, haven't seen it yet, let me try

**Comment by jclusso** [comment]
@iRet if you fix that I'll be so happy :)! I gave up and I think @richrace did to because we both couldn't.

**Comment by iRet** [comment]
@jclusso just fixed ruby strings and updated PR
Still see some issues with html tags but that's enough for today :) will dig it later
![image](https://cloud.githubusercontent.com/assets/46217/6483611/1c0de00a-c29d-11e4-9f5e-59600d2a9e72.png)

**Comment by jclusso** [comment]
Awesome, @iRet! I'll try it out and see how it works

**Comment by iRet** [comment]
@jclusso sorry but it still buggy. Actually I can figure it out for sublime haml package, it's pretty same ported textmate bundle with a minor changes, but python regexp support negative lookahead, so we can say 'end of line but not prepended with comma'. Will try again this weekends.

**Comment by jclusso** [comment]
@iRet cool! I appreciate you trying to fix this

**Comment by jclusso** [comment]
@iRet did you ever get the ruby line working?

**Comment by cannikin** [comment]
Anything mergeable or we still looking at fixes?

**Comment by iRet** [comment]
@jclusso not fully, actually attributes and ruby lines looks ok now, but it caused new issues with haml/html tags
![test_html_haml_-__users_artyom_desktop_-_atom](https://cloud.githubusercontent.com/assets/46217/6695629/dac3fee8-cd0c-11e4-94b8-cf2d12137733.png)
Still had no time for a deeper look into it. And switched to sublime, where I'm using similar fixes but it not causes this tags bug.
I've just updated updated my PR if you interested in testing, another things seems fine as far as I tested.

**Comment by iRet** [comment]
It seems like problem not in rubyline end pattern, just tried to add quotes to it, no effect. And tags higlighted as text not as ruby code.
It could be in html tag start pattern, but it is almost the same like in sublime package, so weird.

**Comment by jclusso** [comment]
Yea, idk if it's of any use but I linked above to a working syntax highlighter for vim written by tpope. I'm not well enough versed to pick the regex apart or i'd do it myself. @iRet 

https://github.com/tpope/vim-haml/blob/master/syntax/haml.vim

**Comment by olivierlacan** [comment]
Anyone still working on this? This is still an issue in `0.21.0`.

**Comment by cannikin** [comment]
Sorry, I was supposed to be transferring ownership of this to someone who had the time to devote to maintaining it. @ezekg offered to take it over a few months ago but I dropped the ball. Anyone else?

**Comment by ezekg** [comment]
@cannikin, if needed, I would like to help out with this still. I use this package every day.

**Comment by cannikin** [comment]
Great! Any idea what steps we go through to transfer ownership? Moving the repo should be easy? But I don't know about the APM package...

**Comment by ezekg** [comment]
I'm not entirely sure. I've never done that. I can look into it later today, though.

As far as I can tell, I think I have this issue resolved by rewriting the `ruby haml.cson` file (essentially just copying the current Sublime text implementation), and cleaning up a couple regexes (adding a little recursion for commas/blocks). I'll post it here soon and see if we can get a new version out to test.

When this issue is fixed, I want to start work on a PHP Haml grammar. I'll also need people to test the Coffee Haml, because I've never used that.

**Comment by olivierlacan** [comment]
I'd be down to help out once @ezekg takes over. 

This is how you transfer ownership: https://atom.io/docs/latest/behind-atom-maintaining-your-packages#transferring-ownership

**Comment by cannikin** [comment]
Great! Transfer initiated! Apparently you just transfer ownership of the repo and the package will magically go over as well.

**Comment by ezekg** [comment]
I think I have everything working nicely. Still a couple issues with filters and trimmed whitespace, but nothing huge. Looking good. I'll continue to test this week before creating a new beta version. :+1: 

![image](https://cloud.githubusercontent.com/assets/6979737/9945479/14a08790-5d53-11e5-9760-f7d0efeaead7.png)

**Comment by jclusso** [comment]
Nice that this finally looks to be getting fixed! Too bad we've started a heavy migration to Slim since Haml is just not nearly as fast. :(

**Comment by olivierlacan** [comment]
@ezekg More :cake: for you!

**Comment by ezekg** [comment]
Everybody test out the new version. Let me know if you find any new issues or edge cases I missed.
