### ISSUE TITLE
Escaped and unescaped ruby code `!=` and `&=` not highlighted

### ISSUE THREAD

**Issue by zinkkrysty** [ezekg/language-haml#23]
Code starting with `!=` or `&=` doesn't get highlighted as per the documentation: http://haml.info/docs/yardoc/file.REFERENCE.html#unescaping_html

```haml
&= "I like cheese & crackers"
!= "I feel <strong>!"
```

**Comment by cannikin** [comment]
I haven't been using Atom lately but if anyone can fix this I'll happily merge it in.

**Comment by ezekg** [comment]
Should be fixed in `0.22.0`.
