### ISSUE TITLE
Interpolated Ruby is not highlighted within plaintext lines

### ISSUE THREAD

**Issue by renchap** [ezekg/language-haml#32]
This is valid haml, interpolation can occur in plain lines :
```haml
%p
  This is test #{test.number}
```
Here `test.number` is not colored as ruby.

**Comment by ezekg** [comment]
Whoooooooo :tada: 

![image](https://cloud.githubusercontent.com/assets/6979737/10650784/f01df9a6-7810-11e5-9e71-3c0a152c9c11.png)
