### ISSUE TITLE
Multiple #{} blocks are not highlighted correctly when separated by a comma

### ISSUE THREAD

**Issue by adampope** [ezekg/language-haml#34]
I have a line that uses multiple interpolation blocks  e.g.  `#{@var}, #{@var2}`

The parser takes the second # to be the start of a comment.  If I remove the comma then the second block is highlighted properly.  When it's highlighted incorrectly all code below it in the document is then not highlighted correctly.

![screen shot 2015-05-19 at 10 01 31](https://cloud.githubusercontent.com/assets/1418872/7699197/1269da84-fe0e-11e4-84c3-723989f4d88c.png)
![screen shot 2015-05-19 at 10 01 41](https://cloud.githubusercontent.com/assets/1418872/7699199/15f35ffe-fe0e-11e4-83a1-fcc8826ec4c1.png)

**Comment by ezekg** [comment]
I'll tackle this next. I believe this is also related to https://github.com/ezekg/language-haml/issues/32.

**Comment by ezekg** [comment]
There's multiple issues with syntax highlighting within plain text, shown below:

![image](https://cloud.githubusercontent.com/assets/6979737/10006820/1572c0ee-6086-11e5-8dfd-2b17feeda52b.png)

This is a tough one, but I'm working on a couple possible solutions.

**Comment by ezekg** [comment]
This is now fixed in `0.22.2`. I am still working on getting proper syntax highlighting for interpolation inside plaintext.
