### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by cannikin** [ezekg/language-haml#36]
I haven't used Atom in a quite a while now so I'm probably not the best person to keep this package up to date. Anyone out there want to take over?

**Comment by richrace** [comment]
I can if no one else wants to.

But not sure if I'll be still using haml and hamlc in the coming months.

**Comment by cannikin** [comment]
Well, no one else has stepped up, you still interested?

**Comment by richrace** [comment]
Yea I can still do it. We could leave this open for a bit to see if anyone else comes forward?

**Comment by ezekg** [comment]
If @richrace isn't interested anymore, I might be able to take it on or at least help him out. I was going to fork this anyway to add true PHP Haml ([MtHaml](https://github.com/arnaud-lb/MtHaml)) support.

**Comment by mendelk** [comment]
@ezekg I use PHP Haml. Any luck on getting this to work?

**Comment by ezekg** [comment]
@mendelk What do you mean? It works for PHP Haml, using the default `.haml` extension. What extension are you using?

**Comment by mendelk** [comment]
@ezekg My bad.

I understood from the comment that it wasn't yet implemented.

Trying it out now, and it in fact works beautifully.

Thanks!

**Comment by ezekg** [comment]
No problemo. I added full support for PHP keywords a couple weeks ago. Let me know if you find any issues. :+1:

**Comment by mendelk** [comment]
Will do.
