### ISSUE TITLE
Commenting out grey out excess text

### ISSUE THREAD

**Issue by freemanoid** [ezekg/language-haml#37]
atom 0.209
language-haml 0.21

![atom_haml_language_bug](https://cloud.githubusercontent.com/assets/180154/8148698/510f51d0-12b1-11e5-8509-8ba22484b603.gif)

```haml
= foo
- if link_to "Home", root_path
  %div
```

I believe that the `-` and `root_path` at the 2 line shouldn't be greyed when I comment out the 1st line.

**Comment by ezekg** [comment]
Hitting this issue as well.

**Comment by pirminis** [comment]
+1

this is extremely annoying issue. the next line after the comment gets comment's CSS classes like it was a commented line. but it's not.

**Comment by Superpencil** [comment]
Same here, in HAML with Rails, if I comment out a line with -# or / or // the subsequent line in italics and some text greyed out as well.

<img width="290" alt="screenshot 2015-07-15 12 26 55" src="https://cloud.githubusercontent.com/assets/3094044/8688299/72f0b6f4-2aee-11e5-8015-9b5ead8e55d7.png">
<img width="349" alt="screenshot 2015-07-15 12 40 12" src="https://cloud.githubusercontent.com/assets/3094044/8688317/a9b8406c-2aee-11e5-8c2a-eee0b7cc934a.png">

**Comment by nekath** [comment]
+1
I think my issue is quite related:

Atom: 1.0.2
language-haml 0.21

`%a.tab#pricing-tab{ href: '#pricing', data: { toggle: 'tab' } } Pricing/Availability`
Whole #pricing-tab and text to the end of the line is grayed out as comment.

**Comment by gkrawiec** [comment]
+1

**Comment by kakipo** [comment]
+1

**Comment by kausters** [comment]
+1 with haml native comments

![haml 1](https://cloud.githubusercontent.com/assets/3408061/9463930/c71406f0-4b28-11e5-87e4-e679e67f012e.png)
![haml 2](https://cloud.githubusercontent.com/assets/3408061/9463934/cbadbce2-4b28-11e5-9410-f8cbedf8a46b.png)

**Comment by ezekg** [comment]
See #20 for current progress on this issue.

**Comment by ezekg** [comment]
Should be fixed in `0.22.0`.
