### ISSUE TITLE
Syntax highlighting breaks when text is on the same line

### ISSUE THREAD

**Issue by shaungrady** [ezekg/language-haml#43]
Broken:
![image](https://cloud.githubusercontent.com/assets/52413/9973340/305c812c-5e26-11e5-8bd5-1e98371a71dd.png)

Not broken:
![image](https://cloud.githubusercontent.com/assets/52413/9973341/375ae34c-5e26-11e5-857e-1837a53820e1.png)

**Comment by ezekg** [comment]
Thanks for the report. This should be fixed in `0.22.1`.
