### ISSUE TITLE
Highlight bug introduced recently (screenshot included)

### ISSUE THREAD

**Issue by Fuffi** [ezekg/language-haml#48]
This kind of bug started very recently:

![screen shot 2015-10-21 at 16 04 34](https://cloud.githubusercontent.com/assets/1379179/10640701/af85b2ba-780d-11e5-83d7-eddf1ca83e4c.png)

**Comment by ezekg** [comment]
Sorry about that. I must've introduced that issue when I added syntax highlight for a few PHP keywords. Fixed in newest version (0.23.2).
