### ISSUE TITLE
Single vs double quotes in new haml syntax

### ISSUE THREAD

**Issue by inkstak** [ezekg/language-haml#51]
Syntax highlighting don't work when using a single quote in new haml syntax :

![shot](https://cloud.githubusercontent.com/assets/474554/11346582/927facf0-921d-11e5-9086-879d5d547e80.png)

**Comment by ezekg** [comment]
Try updating to the latest version. This should've been fixed a few weeks ago.

**Comment by inkstak** [comment]
Yes, I saw that. This doesn't work because of some Atom cache.
Closing and opening Atom was not enough.

I cleaned everything I could and it seems to work.

**Comment by ezekg** [comment]
Great. Usually you can do `⌘+⇧+P`, type reload and select "Window: Reload" – that's what I use while developing/testing this package.
