### ISSUE TITLE
Syntax highlight not working on block comments

### ISSUE THREAD

**Issue by kemelzaidan** [ezekg/language-haml#52]
Syntax highlight is not showing block comments as comments. It happens either on html and haml comments. Eg on a haml comment:

```haml
-#
    .phones
      %ul
        - unless @professional.phone.blank?
          %li= format_phone @professional.phone
        - unless @professional.phone2.blank?
          %li= format_phone @professional.phone2
```

The hole block above should be shown as a comment.

**Comment by ezekg** [comment]
Nice catch. Should be fixed in `0.23.8`.

**Comment by ezekg** [comment]
Reverted those changes, actually. This will need a bit more work to fully support. I'll keep you posted.

**Comment by ezekg** [comment]
Okay, I think this is working now. Let me know if you find any issues.
