### ISSUE TITLE
IE conditional comments make nested code sytax-highted as comments

### ISSUE THREAD

**Issue by pmsaue0** [ezekg/language-haml#54]
In our app we use some conditional `html` tags for versions of IE.  In the `23.4` version of this plugin I was able to successfully see all correct syntax highlighting, but in the latest version, and at least `23.9`, I see everything that's indented in the IE conditional comment as being read by `language-haml` as a comment.  

This makes sense, and is "correct" as the body of the code is technically within the comment, but I don't want that behavior.  Perhaps there is a way to ignore these type of IE comments?  I will paste screenshots.  

![ie-comment-highlighting-bug](https://cloud.githubusercontent.com/assets/13648/11791113/69b78d00-a254-11e5-932b-5e32f7a6fdfc.png)

Thank you! :)

**Comment by ezekg** [comment]
Thanks for the report. Even though the way it is now is like you said, the 'correct' way (and the way the default HTML syntax highlighting handles it), I understand wanting to have syntax highlighting for those big conditional blocks. Check out the newest version (`0.23.14`) for the patch. Let me know if that fixes the issue for you. :+1:

**Comment by pmsaue0** [comment]
This does fix this case for me.  Thanks!   :muscle:

**Comment by ezekg** [comment]
No problem! 👍
