### ISSUE TITLE
Issue with rubocop linter

### ISSUE THREAD

**Issue by jonesmac** [ezekg/language-haml#58]
Please see here - https://github.com/AtomLinter/linter-rubocop/issues/145#issuecomment-235737672

In haml files that use String Interpolation '#{}', it seems to be using an incorrect scope.

**Comment by ezekg** [comment]
I will check this out later this week. In the meantime, pull requests are always welcome!

**Comment by ezekg** [comment]
Hey, I'd love to get some help here. I've tried modifying the scopes, but it breaks the Ruby syntax highlighting for some reason. I'll try to dig in more when I have time, but I'm pretty busy atm.

**Comment by ezekg** [comment]
I believe this is now resolved with #60. Let me know if it is still an issue.
