### ISSUE TITLE
Can't use comment key-binding on version 0.24.4

### ISSUE THREAD

**Issue by ArthurFoucher** [ezekg/language-haml#62]
I'm using the language-haml package to edit haml-coffeescript files in Atom 1.17.0 on my MBP running OSX 10.11.6. 
I updated the package yesterday and since then the `cmd-/` key binding no longer comments out lines. I used the keybinding resolver panel to make sure that it does resolve to `editor:toggle-line-comments` but I'm running out of ways to troubleshoot this issue, any idea ?

Thanks

**Comment by ezekg** [comment]
Hey I just pushed a fix for this and cut a new version, v0.24.5. Let me know if that works!

**Comment by ArthurFoucher** [comment]
Yes it's fixed now ! Thanks for the super quick response 👍

**Comment by ezekg** [comment]
No problem. 🙂
