### ISSUE TITLE
Adds 'end' when autocompleting blocks

### ISSUE THREAD

**Issue by pedantic-git** [ezekg/language-haml#63]
Sorry if I'm misunderstanding something - this could turn out to just be my settings.

It seems like `language-haml` calls into various autocompletions from the `language-ruby`.

When a line ends with `do`, it adds a line below with `end`, which would be correct in Ruby but not in Haml. The same thing doesn't happen for `if`-statements so I'm guessing whatever override you have for those should also apply to blocks?

**Comment by ezekg** [comment]
Good catch. I'll try and see what is causing this. I'm thinking it's something inside: https://github.com/ezekg/language-haml/blob/master/snippets/language-haml.cson.

**Comment by pedantic-git** [comment]
Thanks! I've never worked in Atom's snippets code so I'm afraid I'd be at a loss but let me know if there's anything I can do re: reproducing it etc.

**Comment by ezekg** [comment]
Fixed in v0.25. 👍
