### ISSUE TITLE
Over-Aggressive Indentation

### ISSUE THREAD

**Issue by Fustrate** [ezekg/language-haml#7]
Trying to type multiple siblings in a row tends to create child elements instead.

Type the following:

```haml
.test
.test
.test
```

and you'll see it come out as:

```haml
.test
  .test
    .test
```

Trying to be smart about indentation might be a bit more trouble than it's worth because there's no way to tell if you want empty elements or nested elements. Even in cases with no ambiguity, such as inline content, it wants to indent everything. I'd rather have to hit the tab key myself than have to realign five `td`s in a row.

**Comment by nateq314** [comment]
If this is solved, then why is the first line in a new section being automatically indented? For example if I create a blank, new .haml file and try to type in:
```haml
%p abc
%p def
%p ghi
```

what I actually get is
```haml
%p abc
    %p def
    %p ghi
```

What's going on here? Is this intentional? Suggestions to disable?

**Comment by ezekg** [comment]
@nateq314, you should be able to go to your 'Settings' panel, click 'Packages', then type in 'haml' and select 'Settings' on the language-haml package. After that, scroll down a bit to the 'Ruby Haml Grammar' section and _uncheck_ 'Auto Indent'.

![image](https://cloud.githubusercontent.com/assets/6979737/12394141/ad961196-bdbf-11e5-9f6b-6925a686f11f.png)

**Comment by nateq314** [comment]
Right, but then that results in no indentation ever. All I want is for the cursor to show up at the same indentation level as the previous line. For that to happen, you have to have “Auto Indent” checked. But then doing so results in the issue reported in my previous message.

**Comment by ezekg** [comment]
Hmm, you're right. I'll check it out and push a fix within the next few days. Sorry about that.

**Comment by ezekg** [comment]
Nevermind on that timeframe, I found the issue. I just removed the indent pattern altogether, as it's not ever needed as far as I can get. It only causes issues.

**Comment by nateq314** [comment]
Thanks!
